[project]

name = "pothole"
version = "0.0.1"
requires-python = ">= 3.9"
dependencies = [
  "ipympl",
  "matplotlib",
  "opencv-contrib-python",
  "torch",
]

[build-system]

requires = ["setuptools >= 61.0"]
